version: "3.9"

services:
  # Test Database
  test-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: maplehustle_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d maplehustle_test"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Test Redis
  test-redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Test Application
  test-app:
    build: .
    depends_on:
      test-db:
        condition: service_healthy
      test-redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@test-db:5432/maplehustle_test
      REDIS_URL: redis://test-redis:6379/0
      JWT_SECRET_KEY: test-secret-key-for-testing-only-32-chars
      ENVIRONMENT: testing
      DEBUG: true
    volumes:
      - .:/code
    working_dir: /code
    command: |
      sh -c "
        echo 'Waiting for test database to be ready...' &&
        python -c 'import time; import psycopg2; 
        while True:
          try:
            psycopg2.connect(\"postgresql://postgres:postgres@test-db:5432/maplehustle_test\")
            break
          except:
            time.sleep(1)' &&
        echo 'Creating test database schema...' &&
        python -c 'from app.db.base import Base; from app.db.session import get_engine; engine = get_engine(); Base.metadata.create_all(bind=engine)' &&
        echo 'Running tests...' &&
        python run_tests.py all
      "
